final List<String> exercises = <String>[
  'Cat/Cow',
  'Child\'s Pose',
  'Thread the Needle',
  'Low Lunge',
  'Neck Massage\n With Balls',
  'Bear Hugs and \nSnow Angels',
  'Figure-Four Stretch',
  'Knee to Chest to\n Spinal Twist',
  'Legs Up the Wall',
  'Box Breath',
];

final List<String> descriptions = [
  'Moving between cat and cow yoga poses releases upper-back and neck tension and synchronizes breath and movement, which starts to calm the body and mind. Come into a tabletop position on the floor, with hands under shoulders and knees under hips. As you inhale, drop the belly, press the chest forward and look up. Exhale, tuck the chin toward the chest and round the spine. Move fluidly between the two poses so that with each inhale you come into cow and with each exhale you come into cat. Take three to five breaths.',
  'The child’s pose releases tension in the back and shoulders, gently stretches the hips and has an overall soothing effect. Starting in tabletop, sink your hips back to your heels and settle your chest between your thighs. Your big toes are touching one another and your knees are as far apart as they need to be to let you breathe deeply. Walk your hands out in front of you, stretching through the arms. Your forehead can rest on the ground, or, for a mini massage, place a tennis ball or massage ball under your forehead and gently roll from side to side. (This step stimulates an acupressure point believed to eliminate nervous tension.)',
  'This gentle twist releases shoulder tension, and starts to stretch and loosen the lower back. Start in tabletop position, wrists under shoulders and knees under hips. As you inhale, take the right arm to the sky, palm facing away from the body. Exhale and sweep the right arm under the chest, resting the shoulder on the ground. Turn the right palm up toward the sky and rest the right cheek on the ground. Keep the left palm pressing into the earth or deepen the twist by taking the left hand to the small of your back. Hold for five breaths.\n\n Then, on an inhale sweep the right hand toward the sky for a gentle counter-twist. Exhale, return to the starting position and repeat on the other side.',
  'This exercise begins to open up the psoas muscle, the deepest muscle in the core that connects the spine to the legs. The psoas help move us forward when we walk or run, support internal organs and connect to the diaphragm, directly impacting our breath. Relaxing the psoas allows us to take deeper, diaphragmatic breaths.Come back to tabletop. Step your right foot forward between your hands and slide your left knee farther behind you. Keep your hands on the floor, framing the front foot, or place them on your front knee. Take five to 10 breaths here and switch legs.',
  'This technique helps release neck tension and stimulates the vagus nerve, the driving force behind the parasympathetic nervous system, which impacts sleep and mood. Come down onto your back with a yoga block or thick book under your head. Turn your head to the right and place the ball on your upper neck behind your ear. Take five deep breaths here. Then gently nod “yes” three or four times, nod “no” three or four times. And, switch sides.',
  'These two exercises open the chest, release tension in the back and shoulders and counteract posture problems — poor posture has been shown to affect stress, mood, breathing and circulation.\n\nCome down on your back and place two tennis or massage balls in between your shoulder blades at the top of your spine. (Tip: Using two massage balls in a carrier sack or two tennis balls inside a sock will keep them from rolling away.) Keep your knees bent and feet on the floor. Rest your head on the floor and take your arms out to your sides like cactus arms. Take three to five breaths here. Then, give yourself a hug crossing right arm over left and switch, crossing left arm over right. Repeat these bear hugs a few times. Then, take your arms back out into the cactus shape. Inhale and slowly extend your arms overhead. Exhale and bring the elbows into your waist. Repeat three to five times, trying to keep the arms on the floor throughout the movement. Lift your hips and roll the balls down your spine a few inches and repeat. Keep rolling the balls down your back and repeating the bear hugs and snow angels until you get to the mid-back (where a bra strap or heart rate monitor would be).',
  'This stretch, also known as “supine pigeon” in yoga, opens up the hips, relieves pressure in the lower back and counteracts too much sitting and poor posture. Lie on your back with your knees bent and feet on the floor. Cross your right foot over your left thigh, just above your knee. Stay here, or hold onto the back of your left thigh and gently pull both legs toward you. Flex both feet, and keep your left foot at knee height or higher. Hold for five to 10 breaths and switch sides.',
  'This combination move stretches the hips and lower back. Stretch out your legs and slide them together. Pull your right knee into your chest clasping your fingers around your right shin and gently hug your knee in to stretch your low back and hips. Hold for three breaths. Release your knee and send it across the left leg for a gentle spinal twist. Turn your gaze to the right. Hold for five to 10 breaths and switch sides.',
  'This yoga posture stretches the hamstrings, relieves lower back tension and can help reduce any swelling or cramps that may have built up from sitting or standing for extended periods. Sit with one hip next to a wall. Swing your legs up parallel to the wall as you lean back and rest your upper body on the ground, forming an L shape. If your hamstrings are tight, scoot your hips back a few inches from the wall or put a slight bend in your knees. For added support, you can also place a folded blanket or bolster beneath your low back. This will lift your butt off the ground slightly. Take your right index finger to your nose and gently close the right nostril. Take five to 10 slow breaths in and out through just the left nostril, which lowers blood pressure, body temperature and anxiety. Release the hand and breathe slowly and deeply through both nostrils. Then, press the feet into the wall, lift the hips slightly, and roll to one side. Stay on your side for a few breaths, taking your time to come out of the pose.',
  'This powerful relaxation technique can help clear the mind and unwind the body — Navy SEALs have reportedly been known to use it when their bodies are in fight-or-flight mode. Climb into bed, lie on your back and rest your hands on your belly. Close your eyes and inhale through your nose for a count of four. Hold the inhale for four. Exhale fully to the count of four, making sure all of the air is out of your lungs. Stay empty of breath for a count of four. Repeat the process for three to five minutes. It can be helpful to visualize drawing the perimeter of a square; imagine traveling up one side of the box on the inhale, across one side as you hold the inhale, down the other side of the box on the exhale and across the other side as you hold the exhale.',
];
